services:
  - type: web
    name: fast-collection-backend
    env: node
    rootDir: node_backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_SHEET_URL
        value: "https://docs.google.com/spreadsheets/d/1xC_gMU1TClUFtWYxI2iN6zpquEqdUszPkFhiqgee2jQ/edit?gid=281759884#gid=281759884"
      - key: WORKSHEET_TITLE
        value: "master_data"
      - key: COLLECTION_WORKSHEET_TITLE
        value: "COLLECTION"
